server:
  port: 8111

spring:
  data:
    mongodb:
      uri: <your uri>

sites:
  fishki-url: "http://fishki.net/mix/"
  fishki-div-container-with-image: "div.embed-image-single"

vk:
  app-id: <your_app_id>
  user-id: <your_user_id>
  group-id: <-your_group_id>
  access-token: <your_access_token>
  chunk-size: 10
  time-post-pub-delay: 1500