server:
  port: 8111

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:h2:mem:spring_web_parser;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always

app:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true

env:
  global:
    user-agents-file: "classpath:user-agents.txt"

  parser:
    download-folder-name: "downloaded"
    min-parse-delay-ms: 1500
    max-parse-delay-ms: 4000

    proxy:
      proxy-url: "83.168.74.163"
      proxy-port: 8080

  image-downloader:
    max-retries: 5
    max-concurrency: 10  # Максимальное количество параллельных загрузок изображений

  vk-publisher:
    chunk-size: 10
    delay-between-retries-ms: 1100 # Базовая задержка
    max-delay-ms: 60000 # Максимальная задержка при backoff
    max-retries: 5

vk:
  api:
    base-url: https://api.vk.com
    version: 5.199
    group-id: -96402574


default:
  headers:
    accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    accept-language: "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"
    cache-control: "no-cache"
    connection:
      timeout: 30000


sites:
  fishki:
    fishki-url: "http://fishki.net/mix/"
    fishki-div-container-with-image: "div.embed-image-single"

    headers:
      accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      accept-language: "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"
      cache-control: "no-cache"
      connection:
        timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  config: classpath:log4j2-spring.xml
# recommendation:
#   base-url: "http://127.0.0.1:8000"
ml:
  publish:
    api-key: ${ML_PUBLISH_API_KEY:}
