from __future__ import annotations

import sqlite3
from pathlib import Path
import time
from typing import Iterable, List, Optional

try:
    import psycopg2
    from psycopg2.extras import RealDictCursor
except Exception:  # pragma: no cover - optional dependency
    psycopg2 = None
    RealDictCursor = None


class Storage:
    def __init__(
        self,
        db_path: str | None = None,
        db_url: str | None = None,
        connect_attempts: int = 1,
        connect_delay_sec: float = 0.5,
    ) -> None:
        self.db_path = db_path
        self.db_url = db_url
        source = db_url or db_path or "ml.db"
        self._is_postgres = source.startswith("postgresql://") or source.startswith("postgres://")
        if self._is_postgres:
            if psycopg2 is None:
                raise RuntimeError("Postgres backend requires psycopg2-binary")
            last_error = None
            for attempt in range(1, max(1, connect_attempts) + 1):
                try:
                    self._connection = psycopg2.connect(source)
                    break
                except Exception as exc:  # pylint: disable=broad-except
                    last_error = exc
                    if attempt == connect_attempts:
                        raise
                    time.sleep(connect_delay_sec)
            if last_error is not None and not hasattr(self, "_connection"):
                raise last_error
        else:
            path = Path(source)
            path.parent.mkdir(parents=True, exist_ok=True)
            self._connection = sqlite3.connect(str(path), check_same_thread=False)
            self._connection.row_factory = sqlite3.Row

    def init(self) -> None:
        if self._is_postgres:
            positives_id = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        else:
            positives_id = "INTEGER PRIMARY KEY AUTOINCREMENT"
        self._execute(
            f"""
            CREATE TABLE IF NOT EXISTS positives (
                id {positives_id},
                url TEXT NOT NULL,
                hash TEXT NOT NULL UNIQUE,
                phash TEXT NOT NULL,
                created_at TIMESTAMP,
                active BOOLEAN DEFAULT TRUE
            );
            """
        )
        self._execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_positives_hash ON positives(hash);")
        self._execute(
            """
            CREATE TABLE IF NOT EXISTS kv (
                name TEXT PRIMARY KEY,
                value TEXT
            );
            """
        )

    def upsert_positive(self, *, hash: str, url: str, phash: str, created_at: str) -> None:
        self._execute(
            """
            INSERT INTO positives (hash, url, phash, created_at, active)
            VALUES (?, ?, ?, ?, TRUE)
            ON CONFLICT(hash) DO UPDATE SET
                url=excluded.url,
                phash=excluded.phash,
                created_at=excluded.created_at,
                active=TRUE
            """,
            (hash, url, phash, created_at),
        )

    def list_active_positives(self) -> List[dict]:
        rows = self._fetchall("SELECT id, url, hash, phash FROM positives WHERE active = TRUE")
        return list(rows)

    def iter_positives(self) -> Iterable[tuple[int, dict]]:
        rows = self._fetchall(
            "SELECT id, url, hash, phash, created_at FROM positives WHERE active = TRUE ORDER BY created_at"
        )
        for row in rows:
            phash_value = row["phash"]
            try:
                phash_int = int(phash_value, 16)
            except (TypeError, ValueError):
                continue
            yield phash_int, {
                "id": row["id"],
                "url": row["url"],
                "hash": row["hash"],
                "created_at": row["created_at"],
            }

    def set_last_sync(self, value: str) -> None:
        self.set_value("last_sync", value)

    def get_last_sync(self) -> Optional[str]:
        return self.get_value("last_sync")

    def set_value(self, name: str, value: str) -> None:
        self._execute(
            "INSERT INTO kv(name, value) VALUES(?, ?) "
            "ON CONFLICT(name) DO UPDATE SET value=excluded.value",
            (name, value),
        )

    def get_value(self, name: str) -> Optional[str]:
        row = self._fetchone("SELECT value FROM kv WHERE name=?", (name,))
        if row is None:
            return None
        if isinstance(row, tuple):
            return row[0]
        if hasattr(row, "__getitem__"):
            return row["value"]
        return row.get("value")

    def close(self) -> None:
        self._connection.close()

    def _prepare(self, sql: str) -> str:
        if self._is_postgres:
            return sql.replace("?", "%s")
        return sql

    def _cursor(self):
        if self._is_postgres and RealDictCursor is not None:
            return self._connection.cursor(cursor_factory=RealDictCursor)
        return self._connection.cursor()

    def _execute(self, sql: str, params: tuple | list | None = None) -> None:
        cur = self._cursor()
        try:
            cur.execute(self._prepare(sql), params or ())
            self._connection.commit()
        finally:
            cur.close()

    def _fetchall(self, sql: str, params: tuple | list | None = None) -> list:
        cur = self._cursor()
        try:
            cur.execute(self._prepare(sql), params or ())
            return cur.fetchall()
        finally:
            cur.close()

    def _fetchone(self, sql: str, params: tuple | list | None = None):
        cur = self._cursor()
        try:
            cur.execute(self._prepare(sql), params or ())
            return cur.fetchone()
        finally:
            cur.close()
