server {
    listen 80;
    root /usr/share/nginx/html;

    # React‑SPA: отдаём index.html для любых внутренних роутов
    location / {
        try_files $uri /index.html;
    }

    # Прокси к backend‑контейнеру
    location /api/ {
        proxy_pass http://backend:8111/api/;
    }
}